-- 002_oauth_auth.sql
-- Historical reference only.
--
-- This migration originally combined additive auth changes with destructive
-- cleanup (dropping old auth tables). That shape is unsafe for production
-- cutover because new environments would execute the destructive path
-- immediately.
--
-- The live migration path is now split into:
--   * 002a_oauth_additive.sql  - additive-only, safe to run first
--   * 002b_oauth_cleanup.sql   - destructive cleanup, run later
--
-- This file is intentionally kept as a no-op so historical references and
-- already-applied migration rows remain understandable, while fresh
-- environments do not execute the old destructive behavior.

-- no-op
